### PR TITLE
Fix netevent header structure

### LINKED ISSUE #173: Netevent client dispatch table should not use ebpf structures as type
_netevent_client_dispatch table in netevent_ebpf_ext_event.c is of ebpf_helper_function_addresses_t type.

This structure should be contract with the netevent provider and should not depend on ebpf structures.

### PR DESCRIPTION
**Pull request by LakshK98**
## Description

Fixes #173 by adding separate header structure for netevent that does not depend on ebpf header.

### CODE REVIEW

File: ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.c [hunk 1]
```diff
@@ -63,12 +63,26 @@ _netevent_ebpf_extension_detach_provider(_In_ HANDLE nmr_binding_handle);
 // Structures for attaching to NetEvent (as an NMR client)
 //
 
+typedef struct netevent_ext_header
```
Comment (Alan-Jowett) [inline ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.c:66]: Why are we duplicating this type? Seems like this should be a common one.

Comment (LakshK98) [reply ebpf_extensions/neteventebpfext/netevent_ebpf_ext_event.c:66]: This header is specifically for the NMI interface between netevent ext and internal netevent provider. Using the common (ebpf) header leads to crashes when integrating with the netevent provider.

**Review by Alan-Jowett — APPROVED** [review]
